# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import math

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(705, 651)
        Dialog.setStyleSheet("background-color: #38383f;\n"
" box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);")
        self.oneButton = QtWidgets.QPushButton(Dialog,clicked= lambda : self.prees_it('1'))
        self.oneButton.setGeometry(QtCore.QRect(0, 250, 141, 101))
        self.oneButton.setStyleSheet(" color: rgb(248, 179, 74);\n"
"font-size:16px;")
        self.oneButton.setObjectName("oneButton")
        self.twoButton = QtWidgets.QPushButton(Dialog ,clicked= lambda : self.prees_it('2'))
        self.twoButton.setGeometry(QtCore.QRect(140, 250, 141, 101))
        self.twoButton.setStyleSheet(" color: rgb(248, 179, 74);\n"
"font-size:16px;")
        self.twoButton.setObjectName("twoButton")
        self.threeButton = QtWidgets.QPushButton(Dialog ,clicked= lambda : self.prees_it('3'))
        self.threeButton.setGeometry(QtCore.QRect(280, 250, 141, 101))
        self.threeButton.setStyleSheet(" color: rgb(248, 179, 74);\n"
"font-size:16px;")
        self.threeButton.setObjectName("threeButton")
        self.cButton = QtWidgets.QPushButton(Dialog ,clicked= lambda : self.prees_it(''))
        self.cButton.setGeometry(QtCore.QRect(420, 250, 141, 101))
        self.cButton.setStyleSheet(" color: rgb(248, 179, 74);\n"
"")
        self.cButton.setObjectName("cButton")
        self.sevenButton = QtWidgets.QPushButton(Dialog ,clicked= lambda : self.prees_it('7'))
        self.sevenButton.setGeometry(QtCore.QRect(0, 450, 141, 101))
        self.sevenButton.setStyleSheet(" color: rgb(248, 179, 74);\n"
"font-size:16px;")
        self.sevenButton.setObjectName("sevenButton")
        self.eightButton = QtWidgets.QPushButton(Dialog ,clicked= lambda : self.prees_it('8'))
        self.eightButton.setGeometry(QtCore.QRect(140, 450, 141, 101))
        self.eightButton.setStyleSheet(" color: rgb(248, 179, 74);\n"
"font-size:16px;")
        self.eightButton.setObjectName("eightButton")
        self.nineButton = QtWidgets.QPushButton(Dialog ,clicked= lambda : self.prees_it('9'))
        self.nineButton.setGeometry(QtCore.QRect(280, 450, 141, 101))
        self.nineButton.setStyleSheet(" color: rgb(248, 179, 74);\n"
"font-size:16px;")
        self.nineButton.setObjectName("nineButton")
        self.bozButton = QtWidgets.QPushButton(Dialog ,clicked= lambda : self.remove_it())
        self.bozButton.setGeometry(QtCore.QRect(420, 450, 141, 101))
        self.bozButton.setStyleSheet(" color: rgb(248, 179, 74);\n"
"font-size:16px;")
        self.bozButton.setObjectName("bozButton")
        self.fourButton = QtWidgets.QPushButton(Dialog ,clicked= lambda : self.prees_it('4'))
        self.fourButton.setGeometry(QtCore.QRect(0, 350, 141, 101))
        self.fourButton.setStyleSheet(" color: rgb(248, 179, 74);\n"
"font-size:16px;")
        self.fourButton.setObjectName("fourButton")
        self.fiveButton = QtWidgets.QPushButton(Dialog ,clicked= lambda : self.prees_it('5'))
        self.fiveButton.setGeometry(QtCore.QRect(140, 350, 141, 101))
        self.fiveButton.setStyleSheet(" color: rgb(248, 179, 74);\n"
"font-size:16px;")
        self.fiveButton.setObjectName("fiveButton")
        self.sixButton = QtWidgets.QPushButton(Dialog ,clicked= lambda : self.prees_it('6'))
        self.sixButton.setGeometry(QtCore.QRect(280, 350, 141, 101))
        self.sixButton.setStyleSheet(" color: rgb(248, 179, 74);\n"
"font-size:16px;")
        self.sixButton.setObjectName("sixButton")
        self.percentButton = QtWidgets.QPushButton(Dialog ,clicked= lambda : self.prees_it('%'))
        self.percentButton.setGeometry(QtCore.QRect(420, 350, 141, 101))
        self.percentButton.setStyleSheet(" color: rgb(248, 179, 74);\n"
"font-size:16px;")
        self.percentButton.setObjectName("percentButton")
        self.taghButton = QtWidgets.QPushButton(Dialog ,clicked= lambda : self.prees_it('/'))
        self.taghButton.setGeometry(QtCore.QRect(0, 150, 141, 101))
        self.taghButton.setStyleSheet(" color: rgb(248, 179, 74);\n"
"")
        self.taghButton.setObjectName("taghButton")
        self.jamButton = QtWidgets.QPushButton(Dialog ,clicked= lambda : self.prees_it('+'))
        self.jamButton.setGeometry(QtCore.QRect(140, 150, 141, 101))
        self.jamButton.setStyleSheet(" color: rgb(248, 179, 74);\n"
"")
        self.jamButton.setObjectName("jamButton")
        self.zarbButton = QtWidgets.QPushButton(Dialog ,clicked= lambda : self.prees_it('*'))
        self.zarbButton.setGeometry(QtCore.QRect(280, 150, 141, 101))
        self.zarbButton.setStyleSheet(" color: rgb(248, 179, 74);\n"
"font-size:16px;")
        self.zarbButton.setObjectName("zarbButton")
        self.tafrighButton = QtWidgets.QPushButton(Dialog ,clicked= lambda : self.prees_it('-'))
        self.tafrighButton.setGeometry(QtCore.QRect(420, 150, 141, 101))
        self.tafrighButton.setStyleSheet(" color: rgb(248, 179, 74);\n"
"font-size:16px;")
        self.tafrighButton.setObjectName("tafrighButton")
        self.mosaviButton = QtWidgets.QPushButton(Dialog ,clicked= lambda : self.action_equal())
        self.mosaviButton.setGeometry(QtCore.QRect(420, 550, 141, 101))
        self.mosaviButton.setStyleSheet(" color: rgb(248, 179, 74);\n"
"font-size:16px;")
        self.mosaviButton.setObjectName("mosaviButton")
        self.sefrButton = QtWidgets.QPushButton(Dialog ,clicked= lambda : self.prees_it('0'))
        self.sefrButton.setGeometry(QtCore.QRect(140, 550, 141, 101))
        self.sefrButton.setStyleSheet(" color: rgb(248, 179, 74);\n"
"font-size:16px;")
        self.sefrButton.setObjectName("sefrButton")
        self.jamtafButton = QtWidgets.QPushButton(Dialog ,clicked= lambda : self.gharine())
        self.jamtafButton.setGeometry(QtCore.QRect(0, 550, 141, 101))
        self.jamtafButton.setStyleSheet(" color: rgb(248, 179, 74);\n"
"font-size:16px;")
        self.jamtafButton.setObjectName("jamtafButton")
        self.noghteButton = QtWidgets.QPushButton(Dialog ,clicked= lambda : self.dot())
        self.noghteButton.setGeometry(QtCore.QRect(280, 550, 141, 101))
        self.noghteButton.setStyleSheet(" color: rgb(248, 179, 74);\n"
"font-size:16px;")
        self.noghteButton.setObjectName("noghteButton")
        self.cosButton = QtWidgets.QPushButton(Dialog ,clicked= lambda : self.prees_it('cos'))
        self.cosButton.setGeometry(QtCore.QRect(560, 250, 141, 101))
        self.cosButton.setStyleSheet(" color: rgb(248, 179, 74);\n"
"font-size:16px;")
        self.cosButton.setObjectName("cosButton")
        self.cotButton = QtWidgets.QPushButton(Dialog ,clicked= lambda : self.prees_it('cot'))
        self.cotButton.setGeometry(QtCore.QRect(560, 450, 141, 101))
        self.cotButton.setStyleSheet(" color: rgb(248, 179, 74);\n"
"font-size:16px;")
        self.cotButton.setObjectName("cotButton")
        self.sinButton = QtWidgets.QPushButton(Dialog ,clicked= lambda : self.prees_it('sin'))
        self.sinButton.setGeometry(QtCore.QRect(560, 150, 141, 101))
        self.sinButton.setStyleSheet(" color: rgb(248, 179, 74);\n"
"font-size:16px;")
        self.sinButton.setObjectName("sinButton")
        self.tanButton = QtWidgets.QPushButton(Dialog ,clicked= lambda : self.prees_it('tan'))
        self.tanButton.setGeometry(QtCore.QRect(560, 350, 141, 101))
        self.tanButton.setStyleSheet(" color: rgb(248, 179, 74);\n"
"font-size:16px;")
        self.tanButton.setObjectName("tanButton")
        self.logButton = QtWidgets.QPushButton(Dialog ,clicked= lambda : self.prees_it('log'))
        self.logButton.setGeometry(QtCore.QRect(560, 550, 141, 101))
        self.logButton.setStyleSheet(" color: rgb(248, 179, 74);\n"
"font-size:16px;")
        self.logButton.setObjectName("logButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 701, 151))
        self.label.setStyleSheet("font-size:30px;\n"
"color:#fff;")
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setLineWidth(4)
        self.label.setMidLineWidth(0)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
    def remove_it(self):
            screen = self.label.text()
            screen = screen [:-1]
            self.label.setText(f'{screen}')
    def gharine(self):
           screen = self.label.text()
           if screen[0] == '-':
                self.label.setText(screen.replace("-",''))     
           else:
                self.label.setText(f'-{screen}')     
    def dot(self):
           screen = self.label.text()
           if screen [-1] == '.':
                    pass
           else:
              self.label.setText(f'{screen}.')     
    def prees_it(self,press):
          if press == "":
             self.label.setText(press)  
          else:
             if self.label.text() == '0':
                     self.label.setText('')
             self.label.setText(f'{self.label.text()}{press}')            
    def action_equal(self):
        equation = self.label.text()
        if equation[0] == 't':
                self.label.setText(str(math.tan(int(equation[3:]))))
        elif equation[0] == 's':
                self.label.setText(str(math.sin(int(equation[3:]))))
        elif equation[0] == 'c' and equation[2] == 's':
                self.label.setText(str(math.cos(int(equation[3:]))))
        elif equation[0] == 'c' and equation[2] == 't':
                self.label.setText(str(math.cot(int(equation[3:]))))
        elif equation[0] == 'l':
                self.label.setText(str(math.log2(int(equation[3:]))))
        else:
          try:
             ans = eval(equation)
             self.label.setText(str(ans))
          except:
            self.label.setText("Wrong Input")  
               
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.oneButton.setText(_translate("Dialog", "1"))
        self.twoButton.setText(_translate("Dialog", "2"))
        self.threeButton.setText(_translate("Dialog", "3"))
        self.cButton.setText(_translate("Dialog", "c"))
        self.sevenButton.setText(_translate("Dialog", "7"))
        self.eightButton.setText(_translate("Dialog", "8"))
        self.nineButton.setText(_translate("Dialog", "9"))
        self.bozButton.setText(_translate("Dialog", "<<"))
        self.fourButton.setText(_translate("Dialog", "4"))
        self.fiveButton.setText(_translate("Dialog", "5"))
        self.sixButton.setText(_translate("Dialog", "6"))
        self.percentButton.setText(_translate("Dialog", "%"))
        self.taghButton.setText(_translate("Dialog", "/"))
        self.jamButton.setText(_translate("Dialog", "+"))
        self.zarbButton.setText(_translate("Dialog", "x"))
        self.tafrighButton.setText(_translate("Dialog", "-"))
        self.mosaviButton.setText(_translate("Dialog", "="))
        self.sefrButton.setText(_translate("Dialog", "0"))
        self.jamtafButton.setText(_translate("Dialog", "+/-"))
        self.noghteButton.setText(_translate("Dialog", "."))
        self.cosButton.setText(_translate("Dialog", "cos"))
        self.cotButton.setText(_translate("Dialog", "cot"))
        self.sinButton.setText(_translate("Dialog", "sin"))
        self.tanButton.setText(_translate("Dialog", "tan"))
        self.logButton.setText(_translate("Dialog", "log"))
        self.label.setText(_translate("Dialog", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
